name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE Credentials
        run: gcloud container clusters get-credentials my-gke-cluster --region=us-central1-a

      - name: Install GKE Auth Plugin
        run: |
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin

      - name: Verify GKE Auth Plugin Installation
        run: gcloud components list | grep gke-gcloud-auth-plugin

      - name: Deploy to GKE
        run: |
          kubectl apply -f nginx-deployment.yml
          kubectl apply -f nginx-service.yml
